<script context="module">
	import Section from '../components/misc/Section.svelte';
	import LatestSection from '../components/misc/LatestSection.svelte';
	import Container from '../components/shared/Container.svelte';
	import Dismissable from '../components/shared/Dismissable.svelte';

	export async function load({ fetch }) {
		const [{ blogs }] = await Promise.all([fetch('/data.json').then((r) => r.json())]);
		return {
			props: {
				blogs
			}
		};
	}
</script>

<script>
	export let blogs;
	let blogItems = blogs.items;
	let categories = [];
	function getLatestPosts(count) {
		return blogItems.slice(0, count);
	}
	function getAllCategories() {
		// add the categories to categories array
		// if the category does not already exist in the array
		// then add it
		blogItems.forEach((blog) => {
			if (blog.fields?.category) {
				if (!categories.includes(blog.fields.category)) {
					categories.push(blog.fields.category);
				}
			}
		});
	}
	function getPostByType(cat) {
		return blogItems.filter((item) => item.fields?.category === cat).slice(0, 3);
	}
	$: getAllCategories();
</script>

<Container fluid bgColor="var(--clr-secondary)">
	<Dismissable>All posts are generated by random data.</Dismissable>
	<LatestSection title="Latest" blogs={getLatestPosts(7)} />
</Container>
<Container>
	{#each categories as category}
		{#if category}
			<Section
				title={category}
				blogs={getPostByType(category)}
				moreLink={`/category/${category}`}
				isPaginate
			/>
		{/if}
	{/each}
</Container>
